#!/usr/bin/env bash
set -e

# 1. Rebuild template to ensure latest changes are used
echo "==> Building template..."
./build_template.sh

# 2. Parse arguments and prepare tmp directory
CLEANUP=false
RAILS_ARGS=()

for arg in "$@"; do
  if [ "$arg" == "--cleanup" ]; then
    CLEANUP=true
  else
    RAILS_ARGS+=("$arg")
  fi
done

mkdir -p tmp
APP_NAME="test_app_$(date +%s)"
TEST_APP_DIR="tmp/${APP_NAME}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_PATH="${SCRIPT_DIR}/out/template.rb"

echo "==> Creating test Rails application in ${TEST_APP_DIR}..."
rails new "$TEST_APP_DIR" -m "$TEMPLATE_PATH" "${RAILS_ARGS[@]}"

# 3. Verify Rails application execution
echo "==> Verifying generated Rails application..."

if [ ! -d "$TEST_APP_DIR" ]; then
  echo "Error: Test Rails app directory was not created."
  exit 1
fi

cd "$TEST_APP_DIR"

# Verify key files generated by template
REQUIRED_FILES=(
  "config/initializers/devise.rb"
  "config/initializers/simple_form.rb"
  "lib/templates/erb/scaffold/_form.html.erb"
  "app/models/user.rb"
  "app/controllers/users/registrations_controller.rb"
  "app/controllers/users/sessions_controller.rb"
  "app/controllers/users/omniauth_callbacks_controller.rb"
  "config/routes.rb"
  "config/recurring.yml"
  "Procfile"
  "lib/tasks/setup_heroku_env.rake"
  "lib/tasks/check_gem_versions.rake"
  "config/application.yml.example"
  "AGENTS.md"
  ".ruby-gemset"
)

for file in "${REQUIRED_FILES[@]}"; do
  if [ ! -f "$file" ]; then
    echo "Error: Required file $file was not generated in test application."
    exit 1
  fi
done

# Execute rails runner to verify environment loads and executes correctly
bin/rails runner "
  puts '==> Verifying Rails models and schema...'
  User.count
  ActiveStorage::Blob.count
  ActionText::RichText.count
  SolidQueue::Job.count
  SolidCache::Entry.count
  SolidCable::Message.count
  puts '==> All models and database tables verified successfully!'
"

echo "==> Verifying custom Rake tasks..."
bin/rails -T heroku | grep -q "heroku:setup_env" || {
  echo "Error: heroku:setup_env task not found in bin/rails -T"
  exit 1
}
bin/rails -T setup_heroku_env | grep -q "setup_heroku_env" || {
  echo "Error: setup_heroku_env task not found in bin/rails -T"
  exit 1
}
bin/rails -T gems | grep -q "gems:check_versions" || {
  echo "Error: gems:check_versions task not found in bin/rails -T"
  exit 1
}
echo "==> Custom Rake tasks verified successfully!"

if [ -f ".gitignore" ]; then
  echo "==> Verifying .gitignore contains macOS and JetBrains rules..."
  grep -q "Global macOS ignore rules" .gitignore || {
    echo "Error: Global macOS ignore rules not found in .gitignore"
    exit 1
  }
  grep -q "Global JetBrains ignore rules" .gitignore || {
    echo "Error: Global JetBrains ignore rules not found in .gitignore"
    exit 1
  }
  echo "==> .gitignore rules verified successfully!"
fi

echo "========================================================="
echo " Test Rails application successfully created and verified!"
if [ "$CLEANUP" = true ]; then
  cd "$SCRIPT_DIR"
  rm -rf "$TEST_APP_DIR"
  echo " Cleaned up test application directory: ${TEST_APP_DIR}"
else
  echo " Preserved at: ${TEST_APP_DIR}"
fi
echo "========================================================="
