#!/usr/bin/env bash
set -e

# 1. Rebuild template to ensure latest changes are used
echo "==> Building template..."
./build_template.sh

# 2. Prepare tmp directory
mkdir -p tmp
APP_NAME="test_app_$(date +%s)"
TEST_APP_DIR="tmp/${APP_NAME}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_PATH="${SCRIPT_DIR}/out/template.rb"

echo "==> Creating test Rails application in ${TEST_APP_DIR}..."
rails new "$TEST_APP_DIR" -m "$TEMPLATE_PATH" --skip-git

# 3. Verify Rails application execution
echo "==> Verifying generated Rails application..."

if [ ! -d "$TEST_APP_DIR" ]; then
  echo "Error: Test Rails app directory was not created."
  exit 1
fi

cd "$TEST_APP_DIR"

# Verify key files generated by template
REQUIRED_FILES=(
  "config/initializers/devise.rb"
  "app/models/user.rb"
  "config/routes.rb"
  "config/recurring.yml"
  "config/queue.yml"
  "config/cache.yml"
)

for file in "${REQUIRED_FILES[@]}"; do
  if [ ! -f "$file" ]; then
    echo "Error: Required file $file was not generated in test application."
    exit 1
  fi
done

# Execute rails runner to verify environment loads and executes correctly
bin/rails runner "puts '==> Rails environment loaded successfully!'"

echo "========================================================="
echo " Test Rails application successfully created and verified!"
echo " Preserved at: ${TEST_APP_DIR}"
echo "========================================================="
