#!/usr/bin/env bash
set -e

# 1. Rebuild template to ensure latest changes are used
echo "==> Building template..."
./build_template.sh

# 2. Parse arguments and prepare tmp directory
CLEANUP=false
RAILS_ARGS=()

for arg in "$@"; do
  if [ "$arg" == "--cleanup" ]; then
    CLEANUP=true
  else
    RAILS_ARGS+=("$arg")
  fi
done

mkdir -p tmp
APP_NAME="test_app_$(date +%s)"
TEST_APP_DIR="tmp/${APP_NAME}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_PATH="${SCRIPT_DIR}/out/template.rb"

echo "==> Creating test Rails application in ${TEST_APP_DIR}..."
rails new "$TEST_APP_DIR" -m "$TEMPLATE_PATH" "${RAILS_ARGS[@]}"

# 3. Verify Rails application execution
echo "==> Verifying generated Rails application..."

if [ ! -d "$TEST_APP_DIR" ]; then
  echo "Error: Test Rails app directory was not created."
  exit 1
fi

cd "$TEST_APP_DIR"

# Verify key files generated by template
REQUIRED_FILES=(
  "config/initializers/devise.rb"
  "app/models/user.rb"
  "app/controllers/users/registrations_controller.rb"
  "app/controllers/users/sessions_controller.rb"
  "app/controllers/users/omniauth_callbacks_controller.rb"
  "config/routes.rb"
  "config/recurring.yml"
  "Procfile"
  "script/setup_heroku_env.sh"
  "config/application.yml.example"
  "AGENTS.md"
  ".ruby-gemset"
)

for file in "${REQUIRED_FILES[@]}"; do
  if [ ! -f "$file" ]; then
    echo "Error: Required file $file was not generated in test application."
    exit 1
  fi
done

# Execute rails runner to verify environment loads and executes correctly
bin/rails runner "
  puts '==> Verifying Rails models and schema...'
  User.count
  ActiveStorage::Blob.count
  ActionText::RichText.count
  SolidQueue::Job.count
  SolidCache::Entry.count
  SolidCable::Message.count
  puts '==> All models and database tables verified successfully!'
"

echo "========================================================="
echo " Test Rails application successfully created and verified!"
if [ "$CLEANUP" = true ]; then
  cd "$SCRIPT_DIR"
  rm -rf "$TEST_APP_DIR"
  echo " Cleaned up test application directory: ${TEST_APP_DIR}"
else
  echo " Preserved at: ${TEST_APP_DIR}"
fi
echo "========================================================="
